"""add tickets

Revision ID: aa950216e43b
Revises: 91b6e426e1f6
Create Date: 2024-07-22 16:21:39.688602

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aa950216e43b'
down_revision = '91b6e426e1f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('WAIT_SUPPORT_ANSWER', 'WAIT_USER_ANSWER', 'CLOSED', name='ticketstatusenum').create(op.get_bind())
    op.create_table('tickets',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('status', postgresql.ENUM('WAIT_SUPPORT_ANSWER', 'WAIT_USER_ANSWER', 'CLOSED', name='ticketstatusenum', create_type=False), server_default='WAIT_SUPPORT_ANSWER', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('tickets_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__tickets'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    sa.Enum('WAIT_SUPPORT_ANSWER', 'WAIT_USER_ANSWER', 'CLOSED', name='ticketstatusenum').drop(op.get_bind())
    # ### end Alembic commands ###
