"""add ticket messages

Revision ID: bb1d0f7c96ba
Revises: aa950216e43b
Create Date: 2024-07-22 17:42:12.968728

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb1d0f7c96ba'
down_revision = 'aa950216e43b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_messages',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('ticket_id', sa.BIGINT(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('ticket_messages_ticket_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('ticket_messages_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__ticket_messages'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_messages')
    # ### end Alembic commands ###
